# These are supported funding model platforms

# github: [your_github_username]
# patreon: your_patreon_username
# open_collective: your_open_collective_username
# ko_fi: your_kofi_username
# tidelift: npm/your-package-name
# liberapay: your_liberapay_username
# issuehunt: your_issuehunt_username
# custom: ['https://www.paypal.me/yourname', 'https://buymeacoffee.com/yourname']
